services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
      
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./sample.py"
    depends_on:
      - mysql